export const FETCH_HOME_VIDEOS = "FETCH_HOME_VIDEOS";
export const FETCH_HOME_VIDEOS_START = "FETCH_HOME_VIDEOS_START";
export const FETCH_HOME_VIDEOS_SUCCESS = "FETCH_HOME_VIDEOS_SUCCESS";
export const FETCH_HOME_VIDEOS_FAIL = "FETCH_HOME_VIDEOS_FAIL";

export const SET_SEARCH_TERM = "SET_SEARCH_TERM";

export const FETCH_SEARCH_VIDEOS = "FETCH_SEARCH_VIDEOS";
export const FETCH_SEARCH_VIDEOS_START = "FETCH_SEARCH_VIDEOS_START";
export const FETCH_SEARCH_VIDEOS_SUCCESS = "FETCH_SEARCH_VIDEOS_SUCCESS";
export const FETCH_SEARCH_VIDEOS_FAIL = "FETCH_SEARCH_VIDEOS_FAIL";
export const GET_VIDEO_TIME = "GET_VIDEO_TIME";

export const FETCH_RELATED_VIDEOS = "FETCH_RELATED_VIDEOS";
export const FETCH_RELATED_VIDEOS_START = "FETCH_RELATED_VIDEOS_START";
export const FETCH_RELATED_VIDEOS_SUCCESS = "FETCH_RELATED_VIDEOS_SUCCESS";
export const FETCH_RELATED_VIDEOS_FAIL = "FETCH_RELATED_VIDEOS_FAIL";
